export const wireAndCableProducts = [
  {
    title: "House Wiring: Electrical Building Wire",
    shortName: "House Wiring",
    href: "/housing-wiring-electrical-building-wire",
    image: "/wiresforhome/Safest-Electrical-Wires-For-Home.JPG",
    description: "Electrical building wires for residential and commercial installations.",
  },
  {
    title: "Z+ Electrical Wire",
    shortName: "Z+",
    href: "/electrical-building-wire",
    image: "/wiresforhome/Fire-Retardant-House-Wires.JPG",
    description: "Security-focused electrical wires for safer building wiring.",
  },
  {
    title: "Single Core / Multicore Industrial Cables",
    shortName: "Industrial",
    href: "/single-core-multicore-industrial-cables",
    image: "/wiresforhome/Best-Multicore-3core-4core-Cables.JPG",
    description: "Industrial cable range for dependable power and control applications.",
  },
  {
    title: "3 Core PVC Insulated Flat Cable",
    shortName: "PVC Flat",
    href: "/three-core-pvc-insulated-flat-cable",
    image: "/assets/img/3-core-submersible-cable-PVC.jpg",
    description: "PVC insulated flat cables for submersible and utility requirements.",
  },
  {
    title: "3 Core XLPE Insulated Flat Cable",
    shortName: "XLPE Flat",
    href: "/three-core-xlpe-insulated-flat-cable",
    image: "/assets/img/3-core-submersible-cable-XPLE.jpg",
    description: "XLPE insulated flat cables built for higher thermal performance.",
  },
  {
    title: "Elevator & Escalator Cables",
    shortName: "Elevator",
    href: "/elevator-escalator-cable",
    image: "/assets/img/Elevator-Cable.jpg",
    description: "Flexible cable solutions for elevator and escalator applications.",
  },
  {
    title: "PVC Insulated Power & Control Cable",
    shortName: "PVC Power",
    href: "/pvc-insulated-power-control-cable",
    image: "/assets/img/cable.jpg",
    description: "PVC insulated power and control cables for industrial networks.",
  },
  {
    title: "XLPE Insulated Power & Control Cable",
    shortName: "XLPE Power",
    href: "/xlpe-insulated-power-control-cable",
    image: "/assets/img/cable-wires.jpg",
    description: "XLPE insulated cables for robust power and control performance.",
  },
  {
    title: "Aerial Bunched Cables",
    shortName: "ABC",
    href: "/ab-cable",
    image: "/assets/img/cable-wires.jpg",
    description: "Aerial bunched cables for overhead power distribution.",
  },
] as const;
