export const conductorProducts = [
  {
    title: "All Aluminium Conductor",
    shortName: "AAC",
    href: "/all-aluminum-conductor",
    image: "/new-product-img/conductor/aac.png",
    description: "Lightweight aluminium conductors for overhead transmission and distribution lines.",
    standard: "IS 398 Part 1",
  },
  {
    title: "All Alloy Aluminium Conductor",
    shortName: "AAAC",
    href: "/all-alloy-aluminum-conductor",
    image: "/new-product-img/conductor/aaac.png",
    description: "High strength aluminium alloy conductors designed for dependable line performance.",
    standard: "IS 398 Part 4",
  },
  {
    title: "Aluminium Conductor Steel Reinforced",
    shortName: "ACSR",
    href: "/aluminum-conductor-steel-reinforced",
    image: "/new-product-img/conductor/acsr.png",
    description: "Steel reinforced aluminium conductors for long spans and higher tensile needs.",
    standard: "IS 398 Part 2",
  },
  {
    title: "Aluminium Conductor Alloy Reinforced",
    shortName: "ACAR",
    href: "/aluminum-conductor-alloy-reinforced",
    image: "/new-product-img/conductor/acar.png",
    description: "Aluminium conductors reinforced with alloy strands for efficient power networks.",
    standard: "IS 398",
  },
  {
    title: "All Alloy Aluminium Conductor Steel Reinforced",
    shortName: "AACSR",
    href: "/all-alloy-aluminum-conductor-steel-reinforced",
    image: "/new-product-img/conductor/aacsr.png",
    description: "Alloy aluminium and steel reinforced construction for demanding overhead lines.",
    standard: "IS 398",
  },
  {
    title: "AL-59 Aluminium Alloy Conductor",
    shortName: "AL-59",
    href: "/al-conductor",
    image: "/new-product-img/conductor/al-59.png",
    description: "Modern aluminium alloy conductor for improved conductivity and mechanical strength.",
    standard: "AL-59",
  },
  {
    title: "All Alloy Aluminium Conductor Steel Reinforced Aluminium Wires",
    shortName: "AACSR/AW",
    href: "/all-alloy-aluminum-conductor-steel-reinforced-aluminum-wires",
    image: "/new-product-img/conductor/aacsr-aw.png",
    description: "Special reinforced conductor construction for robust utility applications.",
    standard: "IS 398",
  },
  {
    title: "Drum Handling Practices",
    shortName: "Handling",
    href: "/drum-handling-practices",
    image: "/new-product-img/conductor/dru-handling.png",
    description: "Recommended handling practices for cable and conductor drums at site.",
    standard: "Guide",
  },
] as const;
